### ISSUE TITLE
Plugin won't take status.ts as a route

### ISSUE THREAD

**Issue by mgara** [GiovanniCardamone/fastify-autoroutes#196] opened 2022-11-18 15:32 UTC
### Versions

- **Node Version:** v18.12.1
- **Operating System:** Ubuntu
- **Terminal:** Vscode terminal
### Expected Behavior

List all the routes in the subdir

### Actual Behavior

The route is missing from the list of available routes

### Steps to Reproduce

I just added a new file to the directory with the **same content** as `health.ts`

### Screenshots (Optional)
<img width="987" alt="Screenshot 2022-11-18 at 10 18 38 AM" src="https://user-images.githubusercontent.com/6472786/202741255-f2232a4d-e7a7-4c45-9fe3-022499f4914f.png">

**Comment by mgara** [comment] 2022-11-18 15:33
Ok I added a new one .. it worked .. it looks like it doesn't like the "status.ts" as a route

**Comment by GiovanniCardamone** [comment] 2022-11-18 19:28
That's very strange, I need to investigate, thank you for the report

**Comment by GiovanniCardamone** [comment] 2022-11-20 16:26
i can confirm there is a problem with route `/status` I think is something related to glob, because is not extracted from files

**Comment by mgara** [comment] 2022-11-20 16:50
I think you might as well put it as a "known bug" and close this one ? it's up to you ...

**Comment by GiovanniCardamone** [comment] 2022-11-20 22:45
I think is better if I can solve this. Also I want to investigate if there are more names who fall in the same scenario.

**Comment by mgara** [comment] 2022-12-01 19:21
@GiovanniCardamone  I'm running into glob issues again, now I'm not sure if your expression is wrong or right as this is the first time for me I deep dive into it, where can I send you a loom video for my test ? I don't want to show my company's name.

**Comment by mgara** [comment] 2022-12-01 21:23
I added the required changes to my PR :  #197

**Comment by GiovanniCardamone** [comment] 2022-12-02 22:35
sorry for the delayed response, i also have a lot of work and almost no time for personal project! :(
I hope I can have more free time soon so I can contribute with the open source!

Thank you a lot for the report and the PR. I have merged and released v3.0.2 with your fix

**Closed by GiovanniCardamone** 2022-12-02 22:35 UTC
Labels: bug
